// The starting ("usulan awal") curriculum for Kids Swim: six skills, Level 1-3
// for the four strokes, indicator rubrics, tests, targets and pass rules.
//
// This file is the SOURCE for the seed migration (0049, generated by
// scripts/gen-curriculum-seed.ts and kept in sync by a test). After seeding,
// the database is the source of truth and admin edits it in /admin/penilaian;
// nothing in the app reads this file at runtime. Every rubric text, target
// distance and pass threshold below is a proposal for the SLR teaching team
// to validate -- they are internal SLR targets, not an external standard.

export type SkillSlug = "dasar" | "water_safety" | "bebas" | "dada" | "punggung" | "kupu";
export type SkillKind = "foundation" | "safety" | "stroke";

export type SeedSkill = {
  slug: SkillSlug;
  // canonical name; also used to match an existing group by normalized name
  name: string;
  kind: SkillKind;
  hasLevels: boolean;
  sortOrder: number;
};

export type SeedIndicator = {
  skill: SkillSlug;
  level: 1 | 2 | 3 | null;
  slug: string;
  label: string;
  description: string;
  rubric: string;
  sortOrder: number;
};

export type SeedTestType = {
  skill: SkillSlug;
  code: string;
  label: string;
  measure: "distance_m" | "duration_s" | "checklist";
  levelSpecific: boolean;
  steps?: string[];
  sortOrder: number;
};

export type SeedTarget = {
  testCode: string;
  level: 1 | 2 | 3;
  value: number;
};

export type SeedRule = {
  skill: SkillSlug;
  level: 1 | 2 | 3 | null;
  masteryMinScore: number;
  minEvidenceSessions: number;
  requiresTest: boolean;
};

export const LEVEL_NAMES: Record<1 | 2 | 3, string> = {
  1: "Dasar",
  2: "Pengembangan",
  3: "Penguasaan",
};

export const SKILLS: SeedSkill[] = [
  { slug: "dasar", name: "Dasar", kind: "foundation", hasLevels: false, sortOrder: 1 },
  { slug: "water_safety", name: "Water Safety", kind: "safety", hasLevels: false, sortOrder: 2 },
  { slug: "bebas", name: "Gaya Bebas", kind: "stroke", hasLevels: true, sortOrder: 3 },
  { slug: "dada", name: "Gaya Dada", kind: "stroke", hasLevels: true, sortOrder: 4 },
  { slug: "punggung", name: "Gaya Punggung", kind: "stroke", hasLevels: true, sortOrder: 5 },
  { slug: "kupu", name: "Gaya Kupu-kupu", kind: "stroke", hasLevels: true, sortOrder: 6 },
];

// Generic anchors; each indicator adds concrete examples for stars 5 and 3.
const generic3 = "Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.";

export function indicator(
  skill: SkillSlug,
  level: 1 | 2 | 3 | null,
  slug: string,
  label: string,
  description: string,
  star5: string,
  star3?: string,
  sortOrder = 0
): SeedIndicator {
  return {
    skill,
    level,
    slug,
    label,
    description,
    rubric: `Contoh bintang 5: ${star5} Contoh bintang 3: ${star3 ?? generic3}`,
    sortOrder,
  };
}

// ---------- Dasar (no levels) ----------
const DASAR: SeedIndicator[] = [
  indicator(
    "dasar",
    null,
    "adaptasi_di_air",
    "Adaptasi di Air",
    "Kenyamanan anak di air dan responsnya terhadap instruksi pengajar.",
    "Nyaman dan tenang di air, langsung merespons instruksi tanpa dibujuk.",
    "Nyaman di air dangkal dan mau mengikuti instruksi sederhana setelah didorong atau dibujuk."
  ),
  indicator(
    "dasar",
    null,
    "pernapasan",
    "Pernapasan (bubbling)",
    "Menghembuskan napas di air dan mengambil napas secara terkontrol.",
    "Menghembuskan napas lewat mulut/hidung di dalam air, lalu mengambil napas di permukaan dengan ritme teratur.",
    "Berani memasukkan wajah dan membuat gelembung, tetapi ritme napas belum teratur."
  ),
  indicator(
    "dasar",
    null,
    "meluncur",
    "Meluncur",
    "Posisi streamline dan keseimbangan setelah dorongan.",
    "Posisi streamline (lengan lurus di depan, kepala di antara lengan) dan meluncur stabil setelah dorongan.",
    "Meluncur beberapa detik setelah dorongan, tetapi tubuh belum lurus atau mulai turun."
  ),
  indicator(
    "dasar",
    null,
    "mengapung",
    "Mengapung",
    "Pengenalan posisi dan keseimbangan dengan bantuan yang makin berkurang.",
    "Mengapung seimbang tanpa topangan (telungkup atau telentang).",
    "Mengapung beberapa detik dengan topangan ringan."
  ),
  indicator(
    "dasar",
    null,
    "menyelam",
    "Menyelam",
    "Memasukkan wajah/tubuh dan melakukan tugas bawah air sesuai tahap belajar.",
    "Memasukkan kepala dan tubuh lalu menyelesaikan tugas bawah air sesuai tahap (mis. mengambil benda) dengan tenang.",
    "Memasukkan kepala dan mengambil benda di kedalaman dangkal dengan arahan."
  ),
  indicator(
    "dasar",
    null,
    "sikap_keberanian",
    "Sikap dan Keberanian",
    "Kesediaan mencoba secara aman dan mengikuti arahan. Nilai tinggi untuk kesediaan mencoba dengan aman dan mengikuti arahan, bukan karena anak mengambil risiko.",
    "Mencoba aktivitas baru dengan percaya diri sambil tetap mengikuti aturan dan arahan pengajar. Anak yang bertindak nekat atau menyimpang dari arahan tidak diberi nilai tinggi.",
    "Mau mencoba dengan dorongan; sesekali perlu diingatkan soal aturan."
  ),
];

// ---------- Water Safety (no levels, eight indicators) ----------
const WATER_SAFETY: SeedIndicator[] = [
  indicator(
    "water_safety",
    null,
    "masuk_air",
    "Masuk Air dengan Aman",
    "Menunggu instruksi dan menggunakan cara masuk yang sesuai kondisi.",
    "Menunggu instruksi, lalu memakai cara masuk yang sesuai kedalaman dan kondisi kolam secara mandiri.",
    "Menunggu instruksi, tetapi cara masuk masih perlu dikoreksi."
  ),
  indicator(
    "water_safety",
    null,
    "kembali_ke_permukaan",
    "Kembali ke Permukaan",
    "Kembali ke permukaan dan mengambil napas setelah masuk/terendam dalam latihan terkontrol.",
    "Segera kembali ke permukaan dan mengambil napas dengan tenang setelah terendam dalam latihan terkontrol.",
    "Kembali ke permukaan dengan sedikit panik atau perlu isyarat pengajar."
  ),
  indicator(
    "water_safety",
    null,
    "floating",
    "Floating",
    "Mempertahankan posisi mengapung dengan jalan napas di atas air.",
    "Mempertahankan posisi mengapung dengan wajah/jalan napas di atas air tanpa bantuan fisik selama durasi latihan.",
    "Mengapung dengan jalan napas di atas air, tetapi masih perlu arahan verbal untuk menjaga posisi kepala."
  ),
  indicator(
    "water_safety",
    null,
    "treading_water",
    "Water Trappen / Treading Water",
    "Bertahan tegak sambil bernapas.",
    "Bertahan tegak di air dengan kepala di atas permukaan dan bernapas teratur selama durasi latihan.",
    "Bertahan tegak beberapa saat, tetapi gerakan belum stabil atau kepala sesekali tenggelam."
  ),
  indicator(
    "water_safety",
    null,
    "rotasi_orientasi",
    "Rotasi dan Orientasi",
    "Berubah dari telungkup ke telentang dan mencari tepi/jalan keluar.",
    "Berputar dari telungkup ke telentang secara mandiri lalu mencari dan menunjuk tepi atau jalan keluar.",
    "Dapat berputar, tetapi perlu arahan untuk menemukan tepi."
  ),
  indicator(
    "water_safety",
    null,
    "bergerak_ke_tepi",
    "Bergerak ke Tepi dan Berpegangan",
    "Mencapai tepi, meraih, dan mempertahankan pegangan; tidak mensyaratkan gaya sempurna.",
    "Mencapai tepi dengan gerak apa pun yang efektif, meraih, dan mempertahankan pegangan sampai diarahkan.",
    "Mencapai tepi dan meraih, tetapi pegangan belum stabil."
  ),
  indicator(
    "water_safety",
    null,
    "keluar_dari_air",
    "Keluar dari Air dengan Aman",
    "Keluar melalui tangga atau tepi sesuai target fasilitas.",
    "Keluar melalui tangga atau tepi kolam dengan cara yang benar tanpa dibantu.",
    "Keluar dari air dengan sedikit bantuan atau pengingat."
  ),
  indicator(
    "water_safety",
    null,
    "aturan_keselamatan",
    "Aturan Keselamatan dan Meminta Bantuan",
    "Mengikuti aturan, menunggu pendamping, meminta bantuan, dan tidak masuk air untuk menolong teman.",
    "Mengikuti aturan kolam, menunggu pendamping, meminta bantuan orang dewasa saat perlu, dan tidak masuk air untuk menolong teman.",
    "Umumnya mengikuti aturan, tetapi masih perlu diingatkan."
  ),
];

// ---------- Strokes: five/six aspects x three levels ----------
// star5 per level; the description is shared across levels.
type Aspect = {
  slug: string;
  label: string;
  description: string;
  star5: [string, string, string];
};

function strokeIndicators(skill: SkillSlug, aspects: Aspect[]): SeedIndicator[] {
  const out: SeedIndicator[] = [];
  for (const level of [1, 2, 3] as const) {
    aspects.forEach((a, i) => {
      out.push(
        indicator(
          skill,
          level,
          `l${level}_${a.slug}`,
          a.label,
          a.description,
          a.star5[level - 1],
          undefined,
          level * 10 + i + 1
        )
      );
    });
  }
  return out;
}

const BEBAS = strokeIndicators("bebas", [
  {
    slug: "posisi_tubuh",
    label: "Posisi Tubuh",
    description: "Tubuh horizontal dengan kepala dan pinggul dekat permukaan air.",
    star5: [
      "Tubuh telungkup lurus saat latihan terpisah (meluncur, menendang dengan papan); pinggul tidak turun.",
      "Tubuh tetap horizontal saat berenang gerakan penuh dan berputar ringan mengikuti napas samping.",
      "Posisi tubuh dan rotasi tetap benar dari awal sampai akhir tes, termasuk ketika mulai lelah.",
    ],
  },
  {
    slug: "gerakan_kaki",
    label: "Gerakan Kaki",
    description: "Tendangan dari pangkal paha, lutut lentur, ujung kaki lurus.",
    star5: [
      "Tendangan kecil dan terus-menerus dari pangkal paha (dengan papan); lutut tidak menekuk berlebihan.",
      "Tendangan tetap stabil saat digabung dengan gerakan tangan dan napas samping.",
      "Ritme tendangan konsisten sepanjang tes, tidak melambat atau menekuk berlebihan saat lelah.",
    ],
  },
  {
    slug: "gerakan_tangan",
    label: "Gerakan Tangan",
    description: "Tarikan dan pemulihan lengan bergantian.",
    star5: [
      "Tarikan satu tangan bergantian dalam latihan terpisah: masuk di depan bahu lalu menarik ke belakang.",
      "Tangan bergantian berkelanjutan: masuk di depan bahu, menarik di bawah tubuh, pemulihan dengan siku tinggi.",
      "Tarikan efektif dan teratur sepanjang tes dengan pemulihan lengan yang rileks.",
    ],
  },
  {
    slug: "pernapasan",
    label: "Pernapasan",
    description: "Mengatur napas saat berenang.",
    star5: [
      "Menghembuskan napas di air dan mengambil napas di tepi/papan dengan wajah masuk air.",
      "Napas samping teratur: kepala menoleh ke samping tanpa mengangkat dagu, dengan ritme tetap.",
      "Napas samping teratur sepanjang tes tanpa ritme terputus atau terengah-engah.",
    ],
  },
  {
    slug: "koordinasi",
    label: "Koordinasi Gerakan",
    description: "Kesesuaian gerakan antar komponen (kaki, tangan, napas).",
    star5: [
      "Mulai menggabungkan dua komponen (kaki dengan tangan atau kaki dengan napas) untuk jarak pendek.",
      "Kaki, tangan, dan napas terkoordinasi dengan ritme berkelanjutan dalam satu lintasan tanpa berhenti.",
      "Teknik dan ritme gabungan konsisten sepanjang tes, termasuk ketika mulai lelah.",
    ],
  },
]);

const DADA = strokeIndicators("dada", [
  {
    slug: "posisi_tubuh",
    label: "Posisi Tubuh",
    description: "Tubuh telungkup lurus dengan gerak naik-turun yang terkendali.",
    star5: [
      "Tubuh telungkup lurus saat meluncur dan menendang; kepala sejajar tubuh.",
      "Tubuh naik-turun ringan mengikuti siklus tarik-napas tanpa pinggul tenggelam.",
      "Posisi tubuh dan fase meluncur stabil sepanjang tes.",
    ],
  },
  {
    slug: "gerakan_kaki",
    label: "Gerakan Kaki",
    description: "Tendangan katak simetris.",
    star5: [
      "Tendangan katak: lutut ditekuk ke samping, telapak keluar, dorong dan rapatkan kaki (dengan papan atau berpegangan).",
      "Tendangan katak simetris, bertenaga, dan kaki rapat di akhir; bukan tendangan gunting.",
      "Tendangan simetris dan efektif konsisten sepanjang tes.",
    ],
  },
  {
    slug: "gerakan_tangan",
    label: "Gerakan Tangan",
    description: "Tarikan melingkar ke depan-samping dan kembali di bawah dagu.",
    star5: [
      "Tarikan melingkar ke depan-samping lalu kembali di bawah dagu dalam latihan terpisah.",
      "Tarikan tidak melewati garis bahu dan lengan kembali ke depan dengan mulus.",
      "Tarikan dan pemulihan efisien konsisten sepanjang tes.",
    ],
  },
  {
    slug: "pernapasan",
    label: "Pernapasan",
    description: "Mengambil napas saat kepala terangkat dan menghembuskan di air.",
    star5: [
      "Menghembuskan napas di air dan mengangkat kepala untuk mengambil napas dalam latihan terpisah.",
      "Mengambil napas saat tarikan dan menghembuskan napas saat meluncur secara teratur.",
      "Napas konsisten pada setiap siklus sepanjang tes.",
    ],
  },
  {
    slug: "koordinasi",
    label: "Koordinasi Gerakan",
    description: "Kesesuaian gerakan antar komponen (tangan, kaki, napas).",
    star5: [
      "Menggabungkan dua komponen gerak dengan benar dalam latihan terpisah.",
      "Gerakan antar komponen nyambung tanpa jeda janggal dalam satu lintasan.",
      "Koordinasi konsisten sepanjang tes, termasuk ketika mulai lelah.",
    ],
  },
  {
    slug: "timing",
    label: "Timing",
    description: "Urutan dan waktu pelaksanaan gerakan (tarik-napas-tendang-meluncur).",
    star5: [
      "Mengenal urutan tarik-napas-tendang-meluncur dengan aba-aba atau hitungan pengajar.",
      "Urutan tarik-napas-tendang-meluncur dengan timing yang makin stabil tanpa hitungan.",
      "Timing dan fase meluncur konsisten sepanjang tes.",
    ],
  },
]);

const PUNGGUNG = strokeIndicators("punggung", [
  {
    slug: "posisi_tubuh",
    label: "Posisi Tubuh",
    description: "Tubuh telentang, telinga di air, pinggul dekat permukaan.",
    star5: [
      "Berbaring telentang dengan telinga di air, pinggul naik, dan pandangan ke atas.",
      "Kepala stabil dan tubuh berputar ringan dari sisi ke sisi mengikuti tarikan.",
      "Posisi tubuh dan rotasi benar sepanjang tes, termasuk ketika lelah.",
    ],
  },
  {
    slug: "gerakan_tangan",
    label: "Gerakan Tangan",
    description: "Tarikan lengan bergantian dengan pemulihan melewati atas kepala.",
    star5: [
      "Tarikan satu lengan bergantian dalam latihan terpisah dengan lengan lurus melewati atas kepala.",
      "Tangan bergantian berkelanjutan: masuk dengan kelingking lebih dulu di atas bahu, menarik di bawah tubuh.",
      "Tarikan dan pemulihan konsisten dan rileks sepanjang tes.",
    ],
  },
  {
    slug: "gerakan_kaki",
    label: "Gerakan Kaki",
    description: "Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan.",
    star5: [
      "Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan (dengan atau tanpa papan).",
      "Tendangan stabil saat digabung dengan tangan dan rotasi tubuh.",
      "Ritme tendangan konsisten sepanjang tes.",
    ],
  },
  {
    slug: "pernapasan",
    label: "Pernapasan",
    description: "Bernapas teratur dengan wajah di atas air.",
    star5: [
      "Bernapas bebas dengan wajah di atas air dan tidak menahan napas.",
      "Napas teratur selaras dengan tarikan tangan.",
      "Napas teratur dan konsisten sepanjang tes.",
    ],
  },
  {
    slug: "koordinasi",
    label: "Koordinasi Gerakan",
    description: "Kesesuaian gerakan antar komponen (kaki, tangan, rotasi, napas).",
    star5: [
      "Menggabungkan tendangan dengan satu komponen tangan untuk jarak pendek.",
      "Kaki, tangan, rotasi tubuh, dan napas terkoordinasi secara berkelanjutan.",
      "Koordinasi dan ritme konsisten sepanjang tes.",
    ],
  },
]);

const KUPU = strokeIndicators("kupu", [
  {
    slug: "gerakan_tubuh",
    label: "Gerakan Tubuh",
    description: "Gelombang tubuh dari dada ke pinggul.",
    star5: [
      "Gelombang tubuh sederhana (dada ke pinggul) dalam latihan terpisah atau dengan sirip.",
      "Gelombang tubuh mengalir dan menyatu dengan tendangan dan tarikan.",
      "Gelombang tubuh konsisten sepanjang tes.",
    ],
  },
  {
    slug: "gerakan_kaki",
    label: "Gerakan Kaki",
    description: "Dolphin kick dari pinggul dengan kedua kaki bersama.",
    star5: [
      "Dolphin kick: kedua kaki bersama dari pinggul, termasuk dorongan di bawah air.",
      "Dolphin kick stabil dan berirama sepanjang siklus.",
      "Dolphin kick bertenaga dan konsisten sepanjang tes.",
    ],
  },
  {
    slug: "gerakan_tangan",
    label: "Gerakan Tangan",
    description: "Tarikan kedua tangan bersamaan dan pemulihan di atas air.",
    star5: [
      "Tarikan dua tangan bersamaan (bentuk lubang kunci) dalam latihan terpisah.",
      "Tangan masuk bersamaan selebar bahu dan pemulihan lengan di atas air.",
      "Tarikan dan pemulihan efisien konsisten sepanjang tes.",
    ],
  },
  {
    slug: "pernapasan",
    label: "Pernapasan",
    description: "Mengambil napas ke depan dengan kepala tetap rendah.",
    star5: [
      "Mengambil napas ke depan saat tarikan dalam latihan terpisah.",
      "Napas ke depan dengan kepala rendah dan tepat waktu dengan tarikan.",
      "Napas teratur tanpa mengganggu ritme sepanjang tes.",
    ],
  },
  {
    slug: "koordinasi",
    label: "Koordinasi Gerakan",
    description: "Kesesuaian gerakan kaki, tangan, dan napas dengan timing yang tepat.",
    star5: [
      "Menggabungkan gerak tubuh dengan satu komponen (kaki dengan tangan) untuk jarak pendek.",
      "Kaki, tangan, dan napas terkoordinasi dengan timing yang tepat.",
      "Ritme dan koordinasi konsisten sepanjang tes.",
    ],
  },
]);

export const INDICATORS: SeedIndicator[] = [
  ...DASAR.map((x, i) => ({ ...x, sortOrder: i + 1 })),
  ...WATER_SAFETY.map((x, i) => ({ ...x, sortOrder: i + 1 })),
  ...BEBAS,
  ...DADA,
  ...PUNGGUNG,
  ...KUPU,
];

export function indicatorSeedKey(i: Pick<SeedIndicator, "skill" | "slug">): string {
  return `k1_${i.skill}_${i.slug}`;
}

export const SAFETY_SEQUENCE_STEPS = [
  "Masuk air",
  "Kembali ke permukaan",
  "Floating",
  "Orientasi",
  "Bergerak ke tepi",
  "Berpegangan",
  "Keluar dari air",
];

export const TEST_TYPES: SeedTestType[] = [
  { skill: "bebas", code: "jarak_bebas", label: "Tes Jarak Gaya Bebas", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "dada", code: "jarak_dada", label: "Tes Jarak Gaya Dada", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "punggung", code: "jarak_punggung", label: "Tes Jarak Gaya Punggung", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "kupu", code: "jarak_kupu", label: "Tes Jarak Gaya Kupu-kupu", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "water_safety", code: "floating", label: "Tes Floating", measure: "duration_s", levelSpecific: false, sortOrder: 1 },
  { skill: "water_safety", code: "treading_water", label: "Tes Treading Water", measure: "duration_s", levelSpecific: false, sortOrder: 2 },
  {
    skill: "water_safety",
    code: "rangkaian_keselamatan",
    label: "Rangkaian Keselamatan",
    measure: "checklist",
    levelSpecific: false,
    steps: SAFETY_SEQUENCE_STEPS,
    sortOrder: 3,
  },
];

// Internal SLR starting targets in meters (admin-editable, versioned).
// Floating / Treading / Rangkaian Keselamatan intentionally have NO default
// target: they are measured (duration) or pass/fail, and a "longest hold"
// target is not wanted for Water Safety.
export const TARGETS: SeedTarget[] = [
  ...(["jarak_bebas", "jarak_dada", "jarak_punggung"] as const).flatMap((testCode) => [
    { testCode, level: 1 as const, value: 10 },
    { testCode, level: 2 as const, value: 25 },
    { testCode, level: 3 as const, value: 50 },
  ]),
  { testCode: "jarak_kupu", level: 1, value: 5 },
  { testCode: "jarak_kupu", level: 2, value: 10 },
  { testCode: "jarak_kupu", level: 3, value: 25 },
];

// Proposed pass rules: every required indicator at >= 4 stars in >= 2
// sessions, plus the level's distance test for strokes. Configurable.
export const RULES: SeedRule[] = [
  { skill: "dasar", level: null, masteryMinScore: 4, minEvidenceSessions: 2, requiresTest: false },
  { skill: "water_safety", level: null, masteryMinScore: 4, minEvidenceSessions: 2, requiresTest: false },
  ...(["bebas", "dada", "punggung", "kupu"] as const).flatMap((skill) =>
    ([1, 2, 3] as const).map((level) => ({
      skill,
      level,
      masteryMinScore: 4,
      minEvidenceSessions: 2,
      requiresTest: true,
    }))
  ),
];
