// The starting curriculum for Teen & Adult Swim: the same foundation as Kids
// Swim (six skills, Level 1-3 for the four strokes, stars 1-5, Progress %,
// tests, records) with indicators and wording written for teenagers and adults.
//
// What is deliberately the SAME as Kids: the six skills, the technique
// indicators of every stroke at every level (same aspects, same rubric), the
// meaning of the stars, the pass rule. Indicators that exist in both programs
// share their slug (`seed_key` differs only by its prefix), so results stay
// comparable when a participant changes category.
//
// Source of the seed migration 0054 (generated by scripts/gen-curriculum-seed.ts,
// kept in sync by tests/curriculum-seed-adult.test.ts). After seeding, the
// database is the source of truth and admin edits it in /admin/penilaian.
// Every rubric, target and record value is a proposal for the SLR team.

import {
  INDICATORS as KIDS_INDICATORS,
  RULES,
  SAFETY_SEQUENCE_STEPS,
  SKILLS,
  indicator,
  type SeedIndicator,
  type SeedTarget,
  type SeedTestType,
} from "./definition";

export const ADULT_PROGRAM_NAME = "Teen & Adult Swim";
export const ADULT_KEY_PREFIX = "ta1";

export function adultSeedKey(i: Pick<SeedIndicator, "skill" | "slug">): string {
  return `${ADULT_KEY_PREFIX}_${i.skill}_${i.slug}`;
}

export const ADULT_SKILLS = SKILLS;

// ---------- Dasar (no levels, seven indicators) ----------
const DASAR: SeedIndicator[] = [
  indicator(
    "dasar",
    null,
    "adaptasi_di_air",
    "Adaptasi di Air",
    "Kenyamanan bergerak di air dan merespons instruksi coach.",
    "Bergerak dan berpindah posisi di air dengan nyaman, wajah masuk air tanpa ragu, dan langsung merespons instruksi coach.",
    "Nyaman di air dangkal dan mengikuti instruksi, tetapi masih ragu saat wajah masuk air atau di air yang lebih dalam."
  ),
  indicator(
    "dasar",
    null,
    "kenyamanan_kepercayaan",
    "Kenyamanan dan Kepercayaan Diri di Air",
    "Rasa nyaman dan percaya diri di air, termasuk di kedalaman yang lebih dalam, sambil tetap mengikuti arahan coach. Nilai tinggi untuk ketenangan dan kesediaan mencoba dengan aman, bukan karena mengambil risiko.",
    "Tenang dan percaya diri di air dangkal maupun lebih dalam, mencoba latihan baru sesuai arahan tanpa terburu-buru atau menyimpang dari aturan.",
    "Cukup nyaman di air dangkal; perlu dorongan atau penjelasan ulang untuk mencoba di air yang lebih dalam."
  ),
  indicator(
    "dasar",
    null,
    "pernapasan",
    "Kontrol Napas (bubbling)",
    "Menghembuskan napas di air dan mengambil napas secara terkontrol.",
    "Menghembuskan napas lewat mulut/hidung di dalam air dan mengambil napas di permukaan dengan ritme teratur, tanpa tersedak.",
    "Berani memasukkan wajah dan membuat gelembung, tetapi ritme napas belum teratur atau masih terengah."
  ),
  indicator(
    "dasar",
    null,
    "mengapung",
    "Mengapung",
    "Posisi dan keseimbangan saat mengapung dengan bantuan yang makin berkurang.",
    "Mengapung seimbang tanpa topangan (telungkup atau telentang) dan mempertahankan posisi dengan rileks.",
    "Mengapung beberapa detik dengan topangan ringan atau perlu koreksi posisi."
  ),
  indicator(
    "dasar",
    null,
    "meluncur",
    "Meluncur",
    "Posisi streamline dan keseimbangan setelah dorongan.",
    "Posisi streamline (lengan lurus di depan, kepala di antara lengan) dan meluncur stabil setelah dorongan dari dinding.",
    "Meluncur beberapa detik setelah dorongan, tetapi tubuh belum lurus atau mulai turun."
  ),
  indicator(
    "dasar",
    null,
    "posisi_tubuh",
    "Posisi Tubuh di Air",
    "Menjaga tubuh tetap horizontal dan seimbang di air, baik telungkup maupun telentang.",
    "Tubuh horizontal, kepala sejajar tulang belakang, dan pinggul dekat permukaan, telungkup maupun telentang, tanpa banyak koreksi.",
    "Posisi cukup baik, tetapi pinggul atau kaki sesekali turun dan perlu koreksi."
  ),
  indicator(
    "dasar",
    null,
    "bergerak_mandiri",
    "Bergerak Mandiri di Air",
    "Bergerak maju di air secara mandiri untuk jarak pendek dengan cara yang aman.",
    "Bergerak maju secara mandiri untuk jarak pendek (mis. satu lebar kolam) dengan gerakan terkendali dan tenang.",
    "Bergerak mandiri beberapa meter, tetapi masih perlu berhenti, berpegangan, atau diarahkan."
  ),
];

// ---------- Water Safety (no levels, eight indicators) ----------
const WATER_SAFETY: SeedIndicator[] = [
  indicator(
    "water_safety",
    null,
    "masuk_air",
    "Masuk Air dengan Aman",
    "Menunggu instruksi dan menggunakan cara masuk yang sesuai kondisi.",
    "Menunggu instruksi, lalu memakai cara masuk yang sesuai kedalaman dan kondisi kolam secara mandiri.",
    "Menunggu instruksi, tetapi cara masuk masih perlu dikoreksi."
  ),
  indicator(
    "water_safety",
    null,
    "kembali_ke_permukaan",
    "Kembali ke Permukaan",
    "Kembali ke permukaan dan mengambil napas setelah masuk/terendam dalam latihan terkontrol.",
    "Segera kembali ke permukaan dan mengambil napas dengan tenang setelah terendam dalam latihan terkontrol.",
    "Kembali ke permukaan dengan sedikit panik atau perlu isyarat coach."
  ),
  indicator(
    "water_safety",
    null,
    "floating",
    "Floating dan Istirahat di Air",
    "Mempertahankan posisi mengapung untuk beristirahat dengan jalan napas di atas air.",
    "Mengapung dan beristirahat dengan wajah/jalan napas di atas air tanpa bantuan fisik selama durasi latihan, dengan napas tenang.",
    "Mengapung dengan jalan napas di atas air, tetapi masih perlu arahan verbal atau sesekali mengubah posisi untuk bertahan."
  ),
  indicator(
    "water_safety",
    null,
    "treading_water",
    "Treading Water",
    "Bertahan tegak di air sambil bernapas dan melihat sekitar.",
    "Bertahan tegak di air dengan kepala di atas permukaan dan bernapas teratur selama durasi latihan.",
    "Bertahan tegak beberapa saat, tetapi gerakan belum stabil atau kepala sesekali tenggelam."
  ),
  indicator(
    "water_safety",
    null,
    "rotasi_orientasi",
    "Rotasi dan Orientasi",
    "Berubah dari telungkup ke telentang dan mencari tepi/jalan keluar.",
    "Berputar dari telungkup ke telentang secara mandiri lalu mencari dan menunjuk tepi atau jalan keluar.",
    "Dapat berputar, tetapi perlu arahan untuk menemukan tepi."
  ),
  indicator(
    "water_safety",
    null,
    "bergerak_ke_tepi",
    "Bergerak ke Tepi dan Berpegangan",
    "Kembali ke tepi, meraih, dan mempertahankan pegangan; tidak mensyaratkan gaya sempurna.",
    "Mencapai tepi dengan gerak apa pun yang efektif, meraih, dan mempertahankan pegangan sampai diarahkan.",
    "Mencapai tepi dan meraih, tetapi pegangan belum stabil."
  ),
  indicator(
    "water_safety",
    null,
    "keluar_dari_air",
    "Keluar dari Air dengan Aman",
    "Keluar melalui tangga atau tepi sesuai fasilitas.",
    "Keluar melalui tangga atau tepi kolam dengan cara yang benar tanpa dibantu.",
    "Keluar dari air dengan sedikit bantuan atau pengingat."
  ),
  indicator(
    "water_safety",
    null,
    "aturan_keselamatan",
    "Aturan Keselamatan dan Meminta Bantuan",
    "Mengikuti aturan kolam, meminta bantuan, dan tidak masuk air untuk menolong orang lain.",
    "Mengikuti aturan kolam, meminta bantuan coach atau petugas saat perlu, dan tidak masuk air untuk menolong orang lain.",
    "Umumnya mengikuti aturan, tetapi masih perlu diingatkan."
  ),
];

// ---------- Strokes: the Kids technique indicators, unchanged, plus practical extras ----------
// Same aspects, same rubric text and the same slugs as Kids, so reports are
// consistent and comparable across categories.
const KIDS_STROKES = KIDS_INDICATORS.filter((i) => i.level !== null);

type Extra = { slug: string; label: string; description: string; star5: string; star3: string };

const EXTRA_L2: Extra = {
  slug: "ritme_konsistensi",
  label: "Ritme dan Konsistensi Teknik",
  description: "Menjaga ritme napas, tangan, dan kaki serta kualitas teknik yang sama dari awal sampai akhir lintasan.",
  star5: "Ritme napas, tangan, dan kaki stabil sepanjang satu lintasan penuh tanpa berhenti, dan kualitas teknik tidak berubah dari awal sampai akhir.",
  star3: "Ritme stabil di sebagian lintasan, tetapi mulai tidak teratur menjelang akhir.",
};
const EXTRA_L3_RHYTHM: Extra = {
  ...EXTRA_L2,
  star5: "Ritme dan kualitas teknik konsisten sepanjang beberapa lintasan berturut-turut, termasuk ketika mulai lelah.",
  star3: "Ritme dan teknik konsisten pada lintasan pertama, tetapi menurun pada lintasan berikutnya.",
};
const EXTRA_L3_ENDURANCE: Extra = {
  slug: "teknik_jarak",
  label: "Teknik Saat Jarak Bertambah (Endurance)",
  description: "Menjaga teknik yang benar dan tempo terkendali saat jarak bertambah.",
  star5: "Menyelesaikan jarak target level dengan teknik yang tetap benar dan tempo terkendali sampai akhir, tanpa berhenti untuk mengatur napas.",
  star3: "Menyelesaikan jarak target, tetapi teknik menurun di bagian akhir atau perlu istirahat singkat.",
};

function withExtras(skill: "bebas" | "dada" | "punggung" | "kupu"): SeedIndicator[] {
  const core = KIDS_STROKES.filter((i) => i.skill === skill);
  const coreCount = (level: 1 | 2 | 3) => core.filter((i) => i.level === level).length;
  const extras: SeedIndicator[] = [];
  const add = (level: 2 | 3, e: Extra, n: number) =>
    extras.push(indicator(skill, level, `l${level}_${e.slug}`, e.label, e.description, e.star5, e.star3, level * 10 + coreCount(level) + n));
  add(2, EXTRA_L2, 1);
  add(3, EXTRA_L3_RHYTHM, 1);
  add(3, EXTRA_L3_ENDURANCE, 2);
  return [...core, ...extras];
}

export const ADULT_INDICATORS: SeedIndicator[] = [
  ...DASAR.map((x, i) => ({ ...x, sortOrder: i + 1 })),
  ...WATER_SAFETY.map((x, i) => ({ ...x, sortOrder: i + 1 })),
  ...withExtras("bebas"),
  ...withExtras("dada"),
  ...withExtras("punggung"),
  ...withExtras("kupu"),
];

export const ADULT_TEST_TYPES: SeedTestType[] = [
  { skill: "bebas", code: "jarak_bebas", label: "Tes Jarak Gaya Bebas", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "dada", code: "jarak_dada", label: "Tes Jarak Gaya Dada", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "punggung", code: "jarak_punggung", label: "Tes Jarak Gaya Punggung", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  { skill: "kupu", code: "jarak_kupu", label: "Tes Jarak Gaya Kupu-kupu", measure: "distance_m", levelSpecific: true, sortOrder: 1 },
  // record-only distance (no level target): how far a push glides
  { skill: "dasar", code: "jarak_meluncur", label: "Tes Jarak Meluncur", measure: "distance_m", levelSpecific: false, sortOrder: 1 },
  { skill: "water_safety", code: "floating", label: "Tes Floating", measure: "duration_s", levelSpecific: false, sortOrder: 1 },
  { skill: "water_safety", code: "treading_water", label: "Tes Treading Water", measure: "duration_s", levelSpecific: false, sortOrder: 2 },
  { skill: "water_safety", code: "rangkaian_keselamatan", label: "Rangkaian Keselamatan", measure: "checklist", levelSpecific: false, steps: SAFETY_SEQUENCE_STEPS, sortOrder: 3 },
];

// Level targets in meters (admin-editable, versioned). Records (medals) are separate, below.
export const ADULT_TARGETS: SeedTarget[] = [
  ...(["jarak_bebas", "jarak_dada", "jarak_punggung"] as const).flatMap((testCode) => [
    { testCode, level: 1 as const, value: 10 },
    { testCode, level: 2 as const, value: 25 },
    { testCode, level: 3 as const, value: 50 },
  ]),
  { testCode: "jarak_kupu", level: 1, value: 5 },
  { testCode: "jarak_kupu", level: 2, value: 10 },
  { testCode: "jarak_kupu", level: 3, value: 25 },
];

export const ADULT_RULES = RULES;

// Records (medals) for the program, as agreed: measurable achievements only.
// Existing milestones are changed only while they still hold their original
// starter values, so a correction made in the admin screen is never overwritten.
export const ADULT_EXTRA_SQL = `
-- ---------------------------------------------------------------
-- Rekor (milestone) Teen & Adult: capaian terukur, bukan nilai indikator.
-- Milestone yang sudah ada hanya diubah selama nilainya masih nilai awal,
-- jadi koreksi yang Anda buat di menu edit tidak pernah ditimpa.
-- Tidak ada rekor yang tersimpan saat ini, jadi tidak ada medali yang terdampak.
-- ---------------------------------------------------------------
update public.milestones m
set bronze = 15, silver = 30, gold = 60
from public.programs g
where g.id = m.program_id and g.name = 'Teen & Adult Swim'
  and m.seed_key = 'adult-mengapung' and m.bronze = 10 and m.silver = 20 and m.gold = 40;

update public.milestones m
set bronze = 15, silver = 30, gold = 60
from public.programs g
where g.id = m.program_id and g.name = 'Teen & Adult Swim'
  and m.seed_key = 'adult-treading' and m.bronze = 30 and m.silver = 60 and m.gold = 120;

-- tahan napas tidak masuk daftar rekor baru: dinonaktifkan (tidak dihapus)
update public.milestones m
set active = false
from public.programs g
where g.id = m.program_id and g.name = 'Teen & Adult Swim'
  and m.seed_key = 'adult-tahan-nafas' and m.active and m.bronze = 5 and m.silver = 10 and m.gold = 20;

insert into public.milestones
  (program_id, seed_key, label, level, metric_type, stroke, distance_m, bronze, silver, gold, sort_order)
select p.id, t.seed_key, t.label, t.level, t.metric_type, t.stroke, t.distance_m, t.bronze, t.silver, t.gold, t.sort_order
from public.programs p
cross join (values
  ('adult-meluncur-jarak',  'Jarak Meluncur',        'Dasar',    'jarak_tempuh', 'Meluncur',  null::numeric, 5::numeric, 10::numeric, 15::numeric, 7),
  ('adult-dada-jarak',      'Jarak Gaya Dada',       'Menengah', 'jarak_tempuh', 'Dada',      null,          10,         25,          50,          8),
  ('adult-punggung-jarak',  'Jarak Gaya Punggung',   'Menengah', 'jarak_tempuh', 'Punggung',  null,          10,         25,          50,          9),
  ('adult-kupu-jarak',      'Jarak Gaya Kupu-kupu',  'Mahir',    'jarak_tempuh', 'Kupu-kupu', null,          5,          10,          25,          10)
) as t(seed_key, label, level, metric_type, stroke, distance_m, bronze, silver, gold, sort_order)
where p.name = 'Teen & Adult Swim'
on conflict (seed_key) do nothing;
`;
