import {
  INDICATORS,
  RULES,
  SKILLS,
  TARGETS,
  TEST_TYPES,
  indicatorSeedKey,
} from "./definition";

// Builds supabase/migrations/0049_curriculum_levels_seed.sql from the typed
// definition. The migration file is committed; tests/curriculum-seed.test.ts
// fails if it drifts from this output, so edit definition.ts and re-run
// `npx tsx scripts/gen-curriculum-seed.ts` instead of hand-editing the SQL.

export function seedPayload() {
  return {
    skills: SKILLS.map((s) => ({
      slug: s.slug,
      name: s.name,
      kind: s.kind,
      has_levels: s.hasLevels,
      sort_order: s.sortOrder,
    })),
    indicators: INDICATORS.map((i) => ({
      seed_key: indicatorSeedKey(i),
      skill: i.skill,
      level: i.level,
      label: i.label,
      description: i.description,
      rubric: i.rubric,
      sort_order: i.sortOrder,
    })),
    tests: TEST_TYPES.map((t) => ({
      skill: t.skill,
      code: t.code,
      label: t.label,
      measure: t.measure,
      level_specific: t.levelSpecific,
      steps: t.steps ?? null,
      sort_order: t.sortOrder,
    })),
    targets: TARGETS.map((t) => ({ test: t.testCode, level: t.level, value: t.value })),
    rules: RULES.map((r) => ({
      skill: r.skill,
      level: r.level,
      mastery_min_score: r.masteryMinScore,
      min_evidence_sessions: r.minEvidenceSessions,
      requires_test: r.requiresTest,
    })),
  };
}

const HEADER = `-- Kurikulum Kids Swim (6 skill, Level 1-3 untuk empat gaya): indikator, rubrik,
-- tipe tes, target jarak v1, dan aturan kelulusan USULAN AWAL.
-- GENERATED by scripts/gen-curriculum-seed.ts from src/lib/curriculum/definition.ts
-- -- do not hand-edit; change the definition and regenerate.
--
-- Dormant by design: nothing here changes what pengajar or orang tua see.
-- New indicators are inserted INACTIVE and the program stays on its legacy
-- model until an admin runs set_curriculum_mode() (0048). Existing legacy
-- indicators/groups/names are never renamed, deactivated or deleted here, and
-- no old score is ever mapped to a level. Safe to re-run: anything already
-- seeded (by seed_key / code) is left exactly as an admin may have edited it.
-- Skips entirely when there is no program named 'Kids Swim'.
`;

export function buildSeedSql(): string {
  const json = JSON.stringify(seedPayload(), null, 1);
  if (json.includes("$json$")) throw new Error("seed JSON contains the dollar-quote tag");

  return `${HEADER}
create or replace function pg_temp.norm_label(t text)
returns text
language sql
immutable
as $$
  select btrim(regexp_replace(
    regexp_replace(
      regexp_replace(lower(coalesce(t, '')), '\\([^)]*\\)', ' ', 'g'),
      '[^a-z0-9]+', ' ', 'g'),
    '\\m(dan|di)\\M', ' ', 'g'), ' ');
$$;

do $seed$
declare
  v_data jsonb := $json$${json}$json$::jsonb;
  p uuid;
  item jsonb;
  v_gid uuid;
  v_iid uuid;
  v_tid uuid;
  v_groups jsonb := '{}'::jsonb;
begin
  select id into p from public.programs where name = 'Kids Swim' order by created_at limit 1;
  if p is null then
    return;
  end if;

  -- skills: reuse the program's existing group (by slug, else by name) so
  -- history keeps pointing at the same rows; only the new columns are set.
  for item in select * from jsonb_array_elements(v_data -> 'skills') loop
    select id into v_gid from public.indicator_groups
    where program_id = p and slug = item ->> 'slug';

    if v_gid is null then
      select id into v_gid from public.indicator_groups
      where program_id = p and slug is null
        and pg_temp.norm_label(name) = pg_temp.norm_label(item ->> 'name')
      order by created_at
      limit 1;
    end if;

    if v_gid is null then
      insert into public.indicator_groups (program_id, name, sort_order, active)
      values (p, item ->> 'name', (item ->> 'sort_order')::int, true)
      returning id into v_gid;
    end if;

    update public.indicator_groups
    set slug = item ->> 'slug',
        skill_kind = item ->> 'kind',
        has_levels = (item ->> 'has_levels')::boolean
    where id = v_gid;

    v_groups := v_groups || jsonb_build_object(item ->> 'slug', v_gid::text);
  end loop;

  -- indicators
  for item in select * from jsonb_array_elements(v_data -> 'indicators') loop
    v_gid := (v_groups ->> (item ->> 'skill'))::uuid;

    if exists (select 1 from public.indicators where program_id = p and seed_key = item ->> 'seed_key') then
      continue;
    end if;

    -- Dasar keeps its existing indicators (and their keys, so every old score
    -- still resolves); they just gain a description and rubric.
    if (item ->> 'skill') = 'dasar' then
      select id into v_iid from public.indicators
      where program_id = p and group_id = v_gid and seed_key is null
        and pg_temp.norm_label(label) = pg_temp.norm_label(item ->> 'label')
      order by created_at
      limit 1;
      if v_iid is not null then
        update public.indicators
        set seed_key = item ->> 'seed_key',
            description = item ->> 'description',
            rubric = item ->> 'rubric',
            required = true
        where id = v_iid;
        continue;
      end if;
    end if;

    insert into public.indicators
      (program_id, group_id, key, label, sort_order, active, level, description, rubric, required, seed_key)
    values
      (p, v_gid, item ->> 'seed_key', item ->> 'label', (item ->> 'sort_order')::int, false,
       nullif(item ->> 'level', '')::smallint, item ->> 'description', item ->> 'rubric', true,
       item ->> 'seed_key')
    on conflict (program_id, key) do nothing;
  end loop;

  -- tests
  for item in select * from jsonb_array_elements(v_data -> 'tests') loop
    insert into public.skill_test_types
      (program_id, group_id, code, label, measure, level_specific, steps, sort_order)
    values
      (p, (v_groups ->> (item ->> 'skill'))::uuid, item ->> 'code', item ->> 'label', item ->> 'measure',
       (item ->> 'level_specific')::boolean,
       case when jsonb_typeof(item -> 'steps') = 'array' then item -> 'steps' else null end,
       (item ->> 'sort_order')::int)
    on conflict (program_id, code) do nothing;
  end loop;

  -- targets (version 1; later changes are new versions made in admin)
  for item in select * from jsonb_array_elements(v_data -> 'targets') loop
    select id into v_tid from public.skill_test_types where program_id = p and code = item ->> 'test';
    if v_tid is not null and not exists (
      select 1 from public.skill_test_targets
      where test_type_id = v_tid and coalesce(level, 0) = (item ->> 'level')::int
    ) then
      insert into public.skill_test_targets (test_type_id, level, target_value, version)
      values (v_tid, (item ->> 'level')::smallint, (item ->> 'value')::numeric, 1);
    end if;
  end loop;

  -- rules
  for item in select * from jsonb_array_elements(v_data -> 'rules') loop
    v_gid := (v_groups ->> (item ->> 'skill'))::uuid;
    if not exists (
      select 1 from public.skill_rules
      where group_id = v_gid and coalesce(level, 0) = coalesce((item ->> 'level')::int, 0)
    ) then
      insert into public.skill_rules (group_id, level, mastery_min_score, min_evidence_sessions, requires_test)
      values (v_gid, nullif(item ->> 'level', '')::smallint, (item ->> 'mastery_min_score')::numeric,
              (item ->> 'min_evidence_sessions')::int, (item ->> 'requires_test')::boolean);
    end if;
  end loop;
end
$seed$;
`;
}
