-- Kurikulum Kids Swim (6 skill, Level 1-3 untuk empat gaya): indikator, rubrik,
-- tipe tes, target jarak v1, dan aturan kelulusan USULAN AWAL.
-- GENERATED by scripts/gen-curriculum-seed.ts from src/lib/curriculum/definition.ts
-- -- do not hand-edit; change the definition and regenerate.
--
-- Dormant by design: nothing here changes what pengajar or orang tua see.
-- New indicators are inserted INACTIVE and the program stays on its legacy
-- model until an admin runs set_curriculum_mode() (0048). Existing legacy
-- indicators/groups/names are never renamed, deactivated or deleted here, and
-- no old score is ever mapped to a level. Safe to re-run: anything already
-- seeded (by seed_key / code) is left exactly as an admin may have edited it.
-- Skips entirely when there is no program named 'Kids Swim'.

create or replace function pg_temp.norm_label(t text)
returns text
language sql
immutable
as $$
  select btrim(regexp_replace(
    regexp_replace(
      regexp_replace(lower(coalesce(t, '')), '\([^)]*\)', ' ', 'g'),
      '[^a-z0-9]+', ' ', 'g'),
    '\m(dan|di)\M', ' ', 'g'), ' ');
$$;

do $seed$
declare
  v_data jsonb := $json${
 "skills": [
  {
   "slug": "dasar",
   "name": "Dasar",
   "kind": "foundation",
   "has_levels": false,
   "sort_order": 1
  },
  {
   "slug": "water_safety",
   "name": "Water Safety",
   "kind": "safety",
   "has_levels": false,
   "sort_order": 2
  },
  {
   "slug": "bebas",
   "name": "Gaya Bebas",
   "kind": "stroke",
   "has_levels": true,
   "sort_order": 3
  },
  {
   "slug": "dada",
   "name": "Gaya Dada",
   "kind": "stroke",
   "has_levels": true,
   "sort_order": 4
  },
  {
   "slug": "punggung",
   "name": "Gaya Punggung",
   "kind": "stroke",
   "has_levels": true,
   "sort_order": 5
  },
  {
   "slug": "kupu",
   "name": "Gaya Kupu-kupu",
   "kind": "stroke",
   "has_levels": true,
   "sort_order": 6
  }
 ],
 "indicators": [
  {
   "seed_key": "k1_dasar_adaptasi_di_air",
   "skill": "dasar",
   "level": null,
   "label": "Adaptasi di Air",
   "description": "Kenyamanan anak di air dan responsnya terhadap instruksi pengajar.",
   "rubric": "Contoh bintang 5: Nyaman dan tenang di air, langsung merespons instruksi tanpa dibujuk. Contoh bintang 3: Nyaman di air dangkal dan mau mengikuti instruksi sederhana setelah didorong atau dibujuk.",
   "sort_order": 1
  },
  {
   "seed_key": "k1_dasar_pernapasan",
   "skill": "dasar",
   "level": null,
   "label": "Pernapasan (bubbling)",
   "description": "Menghembuskan napas di air dan mengambil napas secara terkontrol.",
   "rubric": "Contoh bintang 5: Menghembuskan napas lewat mulut/hidung di dalam air, lalu mengambil napas di permukaan dengan ritme teratur. Contoh bintang 3: Berani memasukkan wajah dan membuat gelembung, tetapi ritme napas belum teratur.",
   "sort_order": 2
  },
  {
   "seed_key": "k1_dasar_meluncur",
   "skill": "dasar",
   "level": null,
   "label": "Meluncur",
   "description": "Posisi streamline dan keseimbangan setelah dorongan.",
   "rubric": "Contoh bintang 5: Posisi streamline (lengan lurus di depan, kepala di antara lengan) dan meluncur stabil setelah dorongan. Contoh bintang 3: Meluncur beberapa detik setelah dorongan, tetapi tubuh belum lurus atau mulai turun.",
   "sort_order": 3
  },
  {
   "seed_key": "k1_dasar_mengapung",
   "skill": "dasar",
   "level": null,
   "label": "Mengapung",
   "description": "Pengenalan posisi dan keseimbangan dengan bantuan yang makin berkurang.",
   "rubric": "Contoh bintang 5: Mengapung seimbang tanpa topangan (telungkup atau telentang). Contoh bintang 3: Mengapung beberapa detik dengan topangan ringan.",
   "sort_order": 4
  },
  {
   "seed_key": "k1_dasar_menyelam",
   "skill": "dasar",
   "level": null,
   "label": "Menyelam",
   "description": "Memasukkan wajah/tubuh dan melakukan tugas bawah air sesuai tahap belajar.",
   "rubric": "Contoh bintang 5: Memasukkan kepala dan tubuh lalu menyelesaikan tugas bawah air sesuai tahap (mis. mengambil benda) dengan tenang. Contoh bintang 3: Memasukkan kepala dan mengambil benda di kedalaman dangkal dengan arahan.",
   "sort_order": 5
  },
  {
   "seed_key": "k1_dasar_sikap_keberanian",
   "skill": "dasar",
   "level": null,
   "label": "Sikap dan Keberanian",
   "description": "Kesediaan mencoba secara aman dan mengikuti arahan. Nilai tinggi untuk kesediaan mencoba dengan aman dan mengikuti arahan, bukan karena anak mengambil risiko.",
   "rubric": "Contoh bintang 5: Mencoba aktivitas baru dengan percaya diri sambil tetap mengikuti aturan dan arahan pengajar. Anak yang bertindak nekat atau menyimpang dari arahan tidak diberi nilai tinggi. Contoh bintang 3: Mau mencoba dengan dorongan; sesekali perlu diingatkan soal aturan.",
   "sort_order": 6
  },
  {
   "seed_key": "k1_water_safety_masuk_air",
   "skill": "water_safety",
   "level": null,
   "label": "Masuk Air dengan Aman",
   "description": "Menunggu instruksi dan menggunakan cara masuk yang sesuai kondisi.",
   "rubric": "Contoh bintang 5: Menunggu instruksi, lalu memakai cara masuk yang sesuai kedalaman dan kondisi kolam secara mandiri. Contoh bintang 3: Menunggu instruksi, tetapi cara masuk masih perlu dikoreksi.",
   "sort_order": 1
  },
  {
   "seed_key": "k1_water_safety_kembali_ke_permukaan",
   "skill": "water_safety",
   "level": null,
   "label": "Kembali ke Permukaan",
   "description": "Kembali ke permukaan dan mengambil napas setelah masuk/terendam dalam latihan terkontrol.",
   "rubric": "Contoh bintang 5: Segera kembali ke permukaan dan mengambil napas dengan tenang setelah terendam dalam latihan terkontrol. Contoh bintang 3: Kembali ke permukaan dengan sedikit panik atau perlu isyarat pengajar.",
   "sort_order": 2
  },
  {
   "seed_key": "k1_water_safety_floating",
   "skill": "water_safety",
   "level": null,
   "label": "Floating",
   "description": "Mempertahankan posisi mengapung dengan jalan napas di atas air.",
   "rubric": "Contoh bintang 5: Mempertahankan posisi mengapung dengan wajah/jalan napas di atas air tanpa bantuan fisik selama durasi latihan. Contoh bintang 3: Mengapung dengan jalan napas di atas air, tetapi masih perlu arahan verbal untuk menjaga posisi kepala.",
   "sort_order": 3
  },
  {
   "seed_key": "k1_water_safety_treading_water",
   "skill": "water_safety",
   "level": null,
   "label": "Water Trappen / Treading Water",
   "description": "Bertahan tegak sambil bernapas.",
   "rubric": "Contoh bintang 5: Bertahan tegak di air dengan kepala di atas permukaan dan bernapas teratur selama durasi latihan. Contoh bintang 3: Bertahan tegak beberapa saat, tetapi gerakan belum stabil atau kepala sesekali tenggelam.",
   "sort_order": 4
  },
  {
   "seed_key": "k1_water_safety_rotasi_orientasi",
   "skill": "water_safety",
   "level": null,
   "label": "Rotasi dan Orientasi",
   "description": "Berubah dari telungkup ke telentang dan mencari tepi/jalan keluar.",
   "rubric": "Contoh bintang 5: Berputar dari telungkup ke telentang secara mandiri lalu mencari dan menunjuk tepi atau jalan keluar. Contoh bintang 3: Dapat berputar, tetapi perlu arahan untuk menemukan tepi.",
   "sort_order": 5
  },
  {
   "seed_key": "k1_water_safety_bergerak_ke_tepi",
   "skill": "water_safety",
   "level": null,
   "label": "Bergerak ke Tepi dan Berpegangan",
   "description": "Mencapai tepi, meraih, dan mempertahankan pegangan; tidak mensyaratkan gaya sempurna.",
   "rubric": "Contoh bintang 5: Mencapai tepi dengan gerak apa pun yang efektif, meraih, dan mempertahankan pegangan sampai diarahkan. Contoh bintang 3: Mencapai tepi dan meraih, tetapi pegangan belum stabil.",
   "sort_order": 6
  },
  {
   "seed_key": "k1_water_safety_keluar_dari_air",
   "skill": "water_safety",
   "level": null,
   "label": "Keluar dari Air dengan Aman",
   "description": "Keluar melalui tangga atau tepi sesuai target fasilitas.",
   "rubric": "Contoh bintang 5: Keluar melalui tangga atau tepi kolam dengan cara yang benar tanpa dibantu. Contoh bintang 3: Keluar dari air dengan sedikit bantuan atau pengingat.",
   "sort_order": 7
  },
  {
   "seed_key": "k1_water_safety_aturan_keselamatan",
   "skill": "water_safety",
   "level": null,
   "label": "Aturan Keselamatan dan Meminta Bantuan",
   "description": "Mengikuti aturan, menunggu pendamping, meminta bantuan, dan tidak masuk air untuk menolong teman.",
   "rubric": "Contoh bintang 5: Mengikuti aturan kolam, menunggu pendamping, meminta bantuan orang dewasa saat perlu, dan tidak masuk air untuk menolong teman. Contoh bintang 3: Umumnya mengikuti aturan, tetapi masih perlu diingatkan.",
   "sort_order": 8
  },
  {
   "seed_key": "k1_bebas_l1_posisi_tubuh",
   "skill": "bebas",
   "level": 1,
   "label": "Posisi Tubuh",
   "description": "Tubuh horizontal dengan kepala dan pinggul dekat permukaan air.",
   "rubric": "Contoh bintang 5: Tubuh telungkup lurus saat latihan terpisah (meluncur, menendang dengan papan); pinggul tidak turun. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 11
  },
  {
   "seed_key": "k1_bebas_l1_gerakan_kaki",
   "skill": "bebas",
   "level": 1,
   "label": "Gerakan Kaki",
   "description": "Tendangan dari pangkal paha, lutut lentur, ujung kaki lurus.",
   "rubric": "Contoh bintang 5: Tendangan kecil dan terus-menerus dari pangkal paha (dengan papan); lutut tidak menekuk berlebihan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 12
  },
  {
   "seed_key": "k1_bebas_l1_gerakan_tangan",
   "skill": "bebas",
   "level": 1,
   "label": "Gerakan Tangan",
   "description": "Tarikan dan pemulihan lengan bergantian.",
   "rubric": "Contoh bintang 5: Tarikan satu tangan bergantian dalam latihan terpisah: masuk di depan bahu lalu menarik ke belakang. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 13
  },
  {
   "seed_key": "k1_bebas_l1_pernapasan",
   "skill": "bebas",
   "level": 1,
   "label": "Pernapasan",
   "description": "Mengatur napas saat berenang.",
   "rubric": "Contoh bintang 5: Menghembuskan napas di air dan mengambil napas di tepi/papan dengan wajah masuk air. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 14
  },
  {
   "seed_key": "k1_bebas_l1_koordinasi",
   "skill": "bebas",
   "level": 1,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, napas).",
   "rubric": "Contoh bintang 5: Mulai menggabungkan dua komponen (kaki dengan tangan atau kaki dengan napas) untuk jarak pendek. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 15
  },
  {
   "seed_key": "k1_bebas_l2_posisi_tubuh",
   "skill": "bebas",
   "level": 2,
   "label": "Posisi Tubuh",
   "description": "Tubuh horizontal dengan kepala dan pinggul dekat permukaan air.",
   "rubric": "Contoh bintang 5: Tubuh tetap horizontal saat berenang gerakan penuh dan berputar ringan mengikuti napas samping. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 21
  },
  {
   "seed_key": "k1_bebas_l2_gerakan_kaki",
   "skill": "bebas",
   "level": 2,
   "label": "Gerakan Kaki",
   "description": "Tendangan dari pangkal paha, lutut lentur, ujung kaki lurus.",
   "rubric": "Contoh bintang 5: Tendangan tetap stabil saat digabung dengan gerakan tangan dan napas samping. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 22
  },
  {
   "seed_key": "k1_bebas_l2_gerakan_tangan",
   "skill": "bebas",
   "level": 2,
   "label": "Gerakan Tangan",
   "description": "Tarikan dan pemulihan lengan bergantian.",
   "rubric": "Contoh bintang 5: Tangan bergantian berkelanjutan: masuk di depan bahu, menarik di bawah tubuh, pemulihan dengan siku tinggi. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 23
  },
  {
   "seed_key": "k1_bebas_l2_pernapasan",
   "skill": "bebas",
   "level": 2,
   "label": "Pernapasan",
   "description": "Mengatur napas saat berenang.",
   "rubric": "Contoh bintang 5: Napas samping teratur: kepala menoleh ke samping tanpa mengangkat dagu, dengan ritme tetap. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 24
  },
  {
   "seed_key": "k1_bebas_l2_koordinasi",
   "skill": "bebas",
   "level": 2,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, napas).",
   "rubric": "Contoh bintang 5: Kaki, tangan, dan napas terkoordinasi dengan ritme berkelanjutan dalam satu lintasan tanpa berhenti. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 25
  },
  {
   "seed_key": "k1_bebas_l3_posisi_tubuh",
   "skill": "bebas",
   "level": 3,
   "label": "Posisi Tubuh",
   "description": "Tubuh horizontal dengan kepala dan pinggul dekat permukaan air.",
   "rubric": "Contoh bintang 5: Posisi tubuh dan rotasi tetap benar dari awal sampai akhir tes, termasuk ketika mulai lelah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 31
  },
  {
   "seed_key": "k1_bebas_l3_gerakan_kaki",
   "skill": "bebas",
   "level": 3,
   "label": "Gerakan Kaki",
   "description": "Tendangan dari pangkal paha, lutut lentur, ujung kaki lurus.",
   "rubric": "Contoh bintang 5: Ritme tendangan konsisten sepanjang tes, tidak melambat atau menekuk berlebihan saat lelah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 32
  },
  {
   "seed_key": "k1_bebas_l3_gerakan_tangan",
   "skill": "bebas",
   "level": 3,
   "label": "Gerakan Tangan",
   "description": "Tarikan dan pemulihan lengan bergantian.",
   "rubric": "Contoh bintang 5: Tarikan efektif dan teratur sepanjang tes dengan pemulihan lengan yang rileks. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 33
  },
  {
   "seed_key": "k1_bebas_l3_pernapasan",
   "skill": "bebas",
   "level": 3,
   "label": "Pernapasan",
   "description": "Mengatur napas saat berenang.",
   "rubric": "Contoh bintang 5: Napas samping teratur sepanjang tes tanpa ritme terputus atau terengah-engah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 34
  },
  {
   "seed_key": "k1_bebas_l3_koordinasi",
   "skill": "bebas",
   "level": 3,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, napas).",
   "rubric": "Contoh bintang 5: Teknik dan ritme gabungan konsisten sepanjang tes, termasuk ketika mulai lelah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 35
  },
  {
   "seed_key": "k1_dada_l1_posisi_tubuh",
   "skill": "dada",
   "level": 1,
   "label": "Posisi Tubuh",
   "description": "Tubuh telungkup lurus dengan gerak naik-turun yang terkendali.",
   "rubric": "Contoh bintang 5: Tubuh telungkup lurus saat meluncur dan menendang; kepala sejajar tubuh. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 11
  },
  {
   "seed_key": "k1_dada_l1_gerakan_kaki",
   "skill": "dada",
   "level": 1,
   "label": "Gerakan Kaki",
   "description": "Tendangan katak simetris.",
   "rubric": "Contoh bintang 5: Tendangan katak: lutut ditekuk ke samping, telapak keluar, dorong dan rapatkan kaki (dengan papan atau berpegangan). Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 12
  },
  {
   "seed_key": "k1_dada_l1_gerakan_tangan",
   "skill": "dada",
   "level": 1,
   "label": "Gerakan Tangan",
   "description": "Tarikan melingkar ke depan-samping dan kembali di bawah dagu.",
   "rubric": "Contoh bintang 5: Tarikan melingkar ke depan-samping lalu kembali di bawah dagu dalam latihan terpisah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 13
  },
  {
   "seed_key": "k1_dada_l1_pernapasan",
   "skill": "dada",
   "level": 1,
   "label": "Pernapasan",
   "description": "Mengambil napas saat kepala terangkat dan menghembuskan di air.",
   "rubric": "Contoh bintang 5: Menghembuskan napas di air dan mengangkat kepala untuk mengambil napas dalam latihan terpisah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 14
  },
  {
   "seed_key": "k1_dada_l1_koordinasi",
   "skill": "dada",
   "level": 1,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (tangan, kaki, napas).",
   "rubric": "Contoh bintang 5: Menggabungkan dua komponen gerak dengan benar dalam latihan terpisah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 15
  },
  {
   "seed_key": "k1_dada_l1_timing",
   "skill": "dada",
   "level": 1,
   "label": "Timing",
   "description": "Urutan dan waktu pelaksanaan gerakan (tarik-napas-tendang-meluncur).",
   "rubric": "Contoh bintang 5: Mengenal urutan tarik-napas-tendang-meluncur dengan aba-aba atau hitungan pengajar. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 16
  },
  {
   "seed_key": "k1_dada_l2_posisi_tubuh",
   "skill": "dada",
   "level": 2,
   "label": "Posisi Tubuh",
   "description": "Tubuh telungkup lurus dengan gerak naik-turun yang terkendali.",
   "rubric": "Contoh bintang 5: Tubuh naik-turun ringan mengikuti siklus tarik-napas tanpa pinggul tenggelam. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 21
  },
  {
   "seed_key": "k1_dada_l2_gerakan_kaki",
   "skill": "dada",
   "level": 2,
   "label": "Gerakan Kaki",
   "description": "Tendangan katak simetris.",
   "rubric": "Contoh bintang 5: Tendangan katak simetris, bertenaga, dan kaki rapat di akhir; bukan tendangan gunting. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 22
  },
  {
   "seed_key": "k1_dada_l2_gerakan_tangan",
   "skill": "dada",
   "level": 2,
   "label": "Gerakan Tangan",
   "description": "Tarikan melingkar ke depan-samping dan kembali di bawah dagu.",
   "rubric": "Contoh bintang 5: Tarikan tidak melewati garis bahu dan lengan kembali ke depan dengan mulus. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 23
  },
  {
   "seed_key": "k1_dada_l2_pernapasan",
   "skill": "dada",
   "level": 2,
   "label": "Pernapasan",
   "description": "Mengambil napas saat kepala terangkat dan menghembuskan di air.",
   "rubric": "Contoh bintang 5: Mengambil napas saat tarikan dan menghembuskan napas saat meluncur secara teratur. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 24
  },
  {
   "seed_key": "k1_dada_l2_koordinasi",
   "skill": "dada",
   "level": 2,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (tangan, kaki, napas).",
   "rubric": "Contoh bintang 5: Gerakan antar komponen nyambung tanpa jeda janggal dalam satu lintasan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 25
  },
  {
   "seed_key": "k1_dada_l2_timing",
   "skill": "dada",
   "level": 2,
   "label": "Timing",
   "description": "Urutan dan waktu pelaksanaan gerakan (tarik-napas-tendang-meluncur).",
   "rubric": "Contoh bintang 5: Urutan tarik-napas-tendang-meluncur dengan timing yang makin stabil tanpa hitungan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 26
  },
  {
   "seed_key": "k1_dada_l3_posisi_tubuh",
   "skill": "dada",
   "level": 3,
   "label": "Posisi Tubuh",
   "description": "Tubuh telungkup lurus dengan gerak naik-turun yang terkendali.",
   "rubric": "Contoh bintang 5: Posisi tubuh dan fase meluncur stabil sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 31
  },
  {
   "seed_key": "k1_dada_l3_gerakan_kaki",
   "skill": "dada",
   "level": 3,
   "label": "Gerakan Kaki",
   "description": "Tendangan katak simetris.",
   "rubric": "Contoh bintang 5: Tendangan simetris dan efektif konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 32
  },
  {
   "seed_key": "k1_dada_l3_gerakan_tangan",
   "skill": "dada",
   "level": 3,
   "label": "Gerakan Tangan",
   "description": "Tarikan melingkar ke depan-samping dan kembali di bawah dagu.",
   "rubric": "Contoh bintang 5: Tarikan dan pemulihan efisien konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 33
  },
  {
   "seed_key": "k1_dada_l3_pernapasan",
   "skill": "dada",
   "level": 3,
   "label": "Pernapasan",
   "description": "Mengambil napas saat kepala terangkat dan menghembuskan di air.",
   "rubric": "Contoh bintang 5: Napas konsisten pada setiap siklus sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 34
  },
  {
   "seed_key": "k1_dada_l3_koordinasi",
   "skill": "dada",
   "level": 3,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (tangan, kaki, napas).",
   "rubric": "Contoh bintang 5: Koordinasi konsisten sepanjang tes, termasuk ketika mulai lelah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 35
  },
  {
   "seed_key": "k1_dada_l3_timing",
   "skill": "dada",
   "level": 3,
   "label": "Timing",
   "description": "Urutan dan waktu pelaksanaan gerakan (tarik-napas-tendang-meluncur).",
   "rubric": "Contoh bintang 5: Timing dan fase meluncur konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 36
  },
  {
   "seed_key": "k1_punggung_l1_posisi_tubuh",
   "skill": "punggung",
   "level": 1,
   "label": "Posisi Tubuh",
   "description": "Tubuh telentang, telinga di air, pinggul dekat permukaan.",
   "rubric": "Contoh bintang 5: Berbaring telentang dengan telinga di air, pinggul naik, dan pandangan ke atas. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 11
  },
  {
   "seed_key": "k1_punggung_l1_gerakan_tangan",
   "skill": "punggung",
   "level": 1,
   "label": "Gerakan Tangan",
   "description": "Tarikan lengan bergantian dengan pemulihan melewati atas kepala.",
   "rubric": "Contoh bintang 5: Tarikan satu lengan bergantian dalam latihan terpisah dengan lengan lurus melewati atas kepala. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 12
  },
  {
   "seed_key": "k1_punggung_l1_gerakan_kaki",
   "skill": "punggung",
   "level": 1,
   "label": "Gerakan Kaki",
   "description": "Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan.",
   "rubric": "Contoh bintang 5: Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan (dengan atau tanpa papan). Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 13
  },
  {
   "seed_key": "k1_punggung_l1_pernapasan",
   "skill": "punggung",
   "level": 1,
   "label": "Pernapasan",
   "description": "Bernapas teratur dengan wajah di atas air.",
   "rubric": "Contoh bintang 5: Bernapas bebas dengan wajah di atas air dan tidak menahan napas. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 14
  },
  {
   "seed_key": "k1_punggung_l1_koordinasi",
   "skill": "punggung",
   "level": 1,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, rotasi, napas).",
   "rubric": "Contoh bintang 5: Menggabungkan tendangan dengan satu komponen tangan untuk jarak pendek. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 15
  },
  {
   "seed_key": "k1_punggung_l2_posisi_tubuh",
   "skill": "punggung",
   "level": 2,
   "label": "Posisi Tubuh",
   "description": "Tubuh telentang, telinga di air, pinggul dekat permukaan.",
   "rubric": "Contoh bintang 5: Kepala stabil dan tubuh berputar ringan dari sisi ke sisi mengikuti tarikan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 21
  },
  {
   "seed_key": "k1_punggung_l2_gerakan_tangan",
   "skill": "punggung",
   "level": 2,
   "label": "Gerakan Tangan",
   "description": "Tarikan lengan bergantian dengan pemulihan melewati atas kepala.",
   "rubric": "Contoh bintang 5: Tangan bergantian berkelanjutan: masuk dengan kelingking lebih dulu di atas bahu, menarik di bawah tubuh. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 22
  },
  {
   "seed_key": "k1_punggung_l2_gerakan_kaki",
   "skill": "punggung",
   "level": 2,
   "label": "Gerakan Kaki",
   "description": "Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan.",
   "rubric": "Contoh bintang 5: Tendangan stabil saat digabung dengan tangan dan rotasi tubuh. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 23
  },
  {
   "seed_key": "k1_punggung_l2_pernapasan",
   "skill": "punggung",
   "level": 2,
   "label": "Pernapasan",
   "description": "Bernapas teratur dengan wajah di atas air.",
   "rubric": "Contoh bintang 5: Napas teratur selaras dengan tarikan tangan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 24
  },
  {
   "seed_key": "k1_punggung_l2_koordinasi",
   "skill": "punggung",
   "level": 2,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, rotasi, napas).",
   "rubric": "Contoh bintang 5: Kaki, tangan, rotasi tubuh, dan napas terkoordinasi secara berkelanjutan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 25
  },
  {
   "seed_key": "k1_punggung_l3_posisi_tubuh",
   "skill": "punggung",
   "level": 3,
   "label": "Posisi Tubuh",
   "description": "Tubuh telentang, telinga di air, pinggul dekat permukaan.",
   "rubric": "Contoh bintang 5: Posisi tubuh dan rotasi benar sepanjang tes, termasuk ketika lelah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 31
  },
  {
   "seed_key": "k1_punggung_l3_gerakan_tangan",
   "skill": "punggung",
   "level": 3,
   "label": "Gerakan Tangan",
   "description": "Tarikan lengan bergantian dengan pemulihan melewati atas kepala.",
   "rubric": "Contoh bintang 5: Tarikan dan pemulihan konsisten dan rileks sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 32
  },
  {
   "seed_key": "k1_punggung_l3_gerakan_kaki",
   "skill": "punggung",
   "level": 3,
   "label": "Gerakan Kaki",
   "description": "Tendangan kecil dari pangkal paha, lutut tidak muncul di permukaan.",
   "rubric": "Contoh bintang 5: Ritme tendangan konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 33
  },
  {
   "seed_key": "k1_punggung_l3_pernapasan",
   "skill": "punggung",
   "level": 3,
   "label": "Pernapasan",
   "description": "Bernapas teratur dengan wajah di atas air.",
   "rubric": "Contoh bintang 5: Napas teratur dan konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 34
  },
  {
   "seed_key": "k1_punggung_l3_koordinasi",
   "skill": "punggung",
   "level": 3,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan antar komponen (kaki, tangan, rotasi, napas).",
   "rubric": "Contoh bintang 5: Koordinasi dan ritme konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 35
  },
  {
   "seed_key": "k1_kupu_l1_gerakan_tubuh",
   "skill": "kupu",
   "level": 1,
   "label": "Gerakan Tubuh",
   "description": "Gelombang tubuh dari dada ke pinggul.",
   "rubric": "Contoh bintang 5: Gelombang tubuh sederhana (dada ke pinggul) dalam latihan terpisah atau dengan sirip. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 11
  },
  {
   "seed_key": "k1_kupu_l1_gerakan_kaki",
   "skill": "kupu",
   "level": 1,
   "label": "Gerakan Kaki",
   "description": "Dolphin kick dari pinggul dengan kedua kaki bersama.",
   "rubric": "Contoh bintang 5: Dolphin kick: kedua kaki bersama dari pinggul, termasuk dorongan di bawah air. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 12
  },
  {
   "seed_key": "k1_kupu_l1_gerakan_tangan",
   "skill": "kupu",
   "level": 1,
   "label": "Gerakan Tangan",
   "description": "Tarikan kedua tangan bersamaan dan pemulihan di atas air.",
   "rubric": "Contoh bintang 5: Tarikan dua tangan bersamaan (bentuk lubang kunci) dalam latihan terpisah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 13
  },
  {
   "seed_key": "k1_kupu_l1_pernapasan",
   "skill": "kupu",
   "level": 1,
   "label": "Pernapasan",
   "description": "Mengambil napas ke depan dengan kepala tetap rendah.",
   "rubric": "Contoh bintang 5: Mengambil napas ke depan saat tarikan dalam latihan terpisah. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 14
  },
  {
   "seed_key": "k1_kupu_l1_koordinasi",
   "skill": "kupu",
   "level": 1,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan kaki, tangan, dan napas dengan timing yang tepat.",
   "rubric": "Contoh bintang 5: Menggabungkan gerak tubuh dengan satu komponen (kaki dengan tangan) untuk jarak pendek. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 15
  },
  {
   "seed_key": "k1_kupu_l2_gerakan_tubuh",
   "skill": "kupu",
   "level": 2,
   "label": "Gerakan Tubuh",
   "description": "Gelombang tubuh dari dada ke pinggul.",
   "rubric": "Contoh bintang 5: Gelombang tubuh mengalir dan menyatu dengan tendangan dan tarikan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 21
  },
  {
   "seed_key": "k1_kupu_l2_gerakan_kaki",
   "skill": "kupu",
   "level": 2,
   "label": "Gerakan Kaki",
   "description": "Dolphin kick dari pinggul dengan kedua kaki bersama.",
   "rubric": "Contoh bintang 5: Dolphin kick stabil dan berirama sepanjang siklus. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 22
  },
  {
   "seed_key": "k1_kupu_l2_gerakan_tangan",
   "skill": "kupu",
   "level": 2,
   "label": "Gerakan Tangan",
   "description": "Tarikan kedua tangan bersamaan dan pemulihan di atas air.",
   "rubric": "Contoh bintang 5: Tangan masuk bersamaan selebar bahu dan pemulihan lengan di atas air. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 23
  },
  {
   "seed_key": "k1_kupu_l2_pernapasan",
   "skill": "kupu",
   "level": 2,
   "label": "Pernapasan",
   "description": "Mengambil napas ke depan dengan kepala tetap rendah.",
   "rubric": "Contoh bintang 5: Napas ke depan dengan kepala rendah dan tepat waktu dengan tarikan. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 24
  },
  {
   "seed_key": "k1_kupu_l2_koordinasi",
   "skill": "kupu",
   "level": 2,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan kaki, tangan, dan napas dengan timing yang tepat.",
   "rubric": "Contoh bintang 5: Kaki, tangan, dan napas terkoordinasi dengan timing yang tepat. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 25
  },
  {
   "seed_key": "k1_kupu_l3_gerakan_tubuh",
   "skill": "kupu",
   "level": 3,
   "label": "Gerakan Tubuh",
   "description": "Gelombang tubuh dari dada ke pinggul.",
   "rubric": "Contoh bintang 5: Gelombang tubuh konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 31
  },
  {
   "seed_key": "k1_kupu_l3_gerakan_kaki",
   "skill": "kupu",
   "level": 3,
   "label": "Gerakan Kaki",
   "description": "Dolphin kick dari pinggul dengan kedua kaki bersama.",
   "rubric": "Contoh bintang 5: Dolphin kick bertenaga dan konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 32
  },
  {
   "seed_key": "k1_kupu_l3_gerakan_tangan",
   "skill": "kupu",
   "level": 3,
   "label": "Gerakan Tangan",
   "description": "Tarikan kedua tangan bersamaan dan pemulihan di atas air.",
   "rubric": "Contoh bintang 5: Tarikan dan pemulihan efisien konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 33
  },
  {
   "seed_key": "k1_kupu_l3_pernapasan",
   "skill": "kupu",
   "level": 3,
   "label": "Pernapasan",
   "description": "Mengambil napas ke depan dengan kepala tetap rendah.",
   "rubric": "Contoh bintang 5: Napas teratur tanpa mengganggu ritme sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 34
  },
  {
   "seed_key": "k1_kupu_l3_koordinasi",
   "skill": "kupu",
   "level": 3,
   "label": "Koordinasi Gerakan",
   "description": "Kesesuaian gerakan kaki, tangan, dan napas dengan timing yang tepat.",
   "rubric": "Contoh bintang 5: Ritme dan koordinasi konsisten sepanjang tes. Contoh bintang 3: Sebagian kriteria bintang 5 terlihat dan dapat dilakukan mandiri, tetapi belum konsisten.",
   "sort_order": 35
  }
 ],
 "tests": [
  {
   "skill": "bebas",
   "code": "jarak_bebas",
   "label": "Tes Jarak Gaya Bebas",
   "measure": "distance_m",
   "level_specific": true,
   "steps": null,
   "sort_order": 1
  },
  {
   "skill": "dada",
   "code": "jarak_dada",
   "label": "Tes Jarak Gaya Dada",
   "measure": "distance_m",
   "level_specific": true,
   "steps": null,
   "sort_order": 1
  },
  {
   "skill": "punggung",
   "code": "jarak_punggung",
   "label": "Tes Jarak Gaya Punggung",
   "measure": "distance_m",
   "level_specific": true,
   "steps": null,
   "sort_order": 1
  },
  {
   "skill": "kupu",
   "code": "jarak_kupu",
   "label": "Tes Jarak Gaya Kupu-kupu",
   "measure": "distance_m",
   "level_specific": true,
   "steps": null,
   "sort_order": 1
  },
  {
   "skill": "water_safety",
   "code": "floating",
   "label": "Tes Floating",
   "measure": "duration_s",
   "level_specific": false,
   "steps": null,
   "sort_order": 1
  },
  {
   "skill": "water_safety",
   "code": "treading_water",
   "label": "Tes Treading Water",
   "measure": "duration_s",
   "level_specific": false,
   "steps": null,
   "sort_order": 2
  },
  {
   "skill": "water_safety",
   "code": "rangkaian_keselamatan",
   "label": "Rangkaian Keselamatan",
   "measure": "checklist",
   "level_specific": false,
   "steps": [
    "Masuk air",
    "Kembali ke permukaan",
    "Floating",
    "Orientasi",
    "Bergerak ke tepi",
    "Berpegangan",
    "Keluar dari air"
   ],
   "sort_order": 3
  }
 ],
 "targets": [
  {
   "test": "jarak_bebas",
   "level": 1,
   "value": 10
  },
  {
   "test": "jarak_bebas",
   "level": 2,
   "value": 25
  },
  {
   "test": "jarak_bebas",
   "level": 3,
   "value": 50
  },
  {
   "test": "jarak_dada",
   "level": 1,
   "value": 10
  },
  {
   "test": "jarak_dada",
   "level": 2,
   "value": 25
  },
  {
   "test": "jarak_dada",
   "level": 3,
   "value": 50
  },
  {
   "test": "jarak_punggung",
   "level": 1,
   "value": 10
  },
  {
   "test": "jarak_punggung",
   "level": 2,
   "value": 25
  },
  {
   "test": "jarak_punggung",
   "level": 3,
   "value": 50
  },
  {
   "test": "jarak_kupu",
   "level": 1,
   "value": 5
  },
  {
   "test": "jarak_kupu",
   "level": 2,
   "value": 10
  },
  {
   "test": "jarak_kupu",
   "level": 3,
   "value": 25
  }
 ],
 "rules": [
  {
   "skill": "dasar",
   "level": null,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": false
  },
  {
   "skill": "water_safety",
   "level": null,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": false
  },
  {
   "skill": "bebas",
   "level": 1,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "bebas",
   "level": 2,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "bebas",
   "level": 3,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "dada",
   "level": 1,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "dada",
   "level": 2,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "dada",
   "level": 3,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "punggung",
   "level": 1,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "punggung",
   "level": 2,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "punggung",
   "level": 3,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "kupu",
   "level": 1,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "kupu",
   "level": 2,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  },
  {
   "skill": "kupu",
   "level": 3,
   "mastery_min_score": 4,
   "min_evidence_sessions": 2,
   "requires_test": true
  }
 ]
}$json$::jsonb;
  p uuid;
  item jsonb;
  v_gid uuid;
  v_iid uuid;
  v_tid uuid;
  v_groups jsonb := '{}'::jsonb;
begin
  select id into p from public.programs where name = 'Kids Swim' order by created_at limit 1;
  if p is null then
    return;
  end if;

  -- skills: reuse the program's existing group (by slug, else by name) so
  -- history keeps pointing at the same rows; only the new columns are set.
  for item in select * from jsonb_array_elements(v_data -> 'skills') loop
    select id into v_gid from public.indicator_groups
    where program_id = p and slug = item ->> 'slug';

    if v_gid is null then
      select id into v_gid from public.indicator_groups
      where program_id = p and slug is null
        and pg_temp.norm_label(name) = pg_temp.norm_label(item ->> 'name')
      order by created_at
      limit 1;
    end if;

    if v_gid is null then
      insert into public.indicator_groups (program_id, name, sort_order, active)
      values (p, item ->> 'name', (item ->> 'sort_order')::int, true)
      returning id into v_gid;
    end if;

    update public.indicator_groups
    set slug = item ->> 'slug',
        skill_kind = item ->> 'kind',
        has_levels = (item ->> 'has_levels')::boolean
    where id = v_gid;

    v_groups := v_groups || jsonb_build_object(item ->> 'slug', v_gid::text);
  end loop;

  -- indicators
  for item in select * from jsonb_array_elements(v_data -> 'indicators') loop
    v_gid := (v_groups ->> (item ->> 'skill'))::uuid;

    if exists (select 1 from public.indicators where program_id = p and seed_key = item ->> 'seed_key') then
      continue;
    end if;

    -- Dasar keeps its existing indicators (and their keys, so every old score
    -- still resolves); they just gain a description and rubric.
    if (item ->> 'skill') = 'dasar' then
      select id into v_iid from public.indicators
      where program_id = p and group_id = v_gid and seed_key is null
        and pg_temp.norm_label(label) = pg_temp.norm_label(item ->> 'label')
      order by created_at
      limit 1;
      if v_iid is not null then
        update public.indicators
        set seed_key = item ->> 'seed_key',
            description = item ->> 'description',
            rubric = item ->> 'rubric',
            required = true
        where id = v_iid;
        continue;
      end if;
    end if;

    insert into public.indicators
      (program_id, group_id, key, label, sort_order, active, level, description, rubric, required, seed_key)
    values
      (p, v_gid, item ->> 'seed_key', item ->> 'label', (item ->> 'sort_order')::int, false,
       nullif(item ->> 'level', '')::smallint, item ->> 'description', item ->> 'rubric', true,
       item ->> 'seed_key')
    on conflict (program_id, key) do nothing;
  end loop;

  -- tests
  for item in select * from jsonb_array_elements(v_data -> 'tests') loop
    insert into public.skill_test_types
      (program_id, group_id, code, label, measure, level_specific, steps, sort_order)
    values
      (p, (v_groups ->> (item ->> 'skill'))::uuid, item ->> 'code', item ->> 'label', item ->> 'measure',
       (item ->> 'level_specific')::boolean,
       case when jsonb_typeof(item -> 'steps') = 'array' then item -> 'steps' else null end,
       (item ->> 'sort_order')::int)
    on conflict (program_id, code) do nothing;
  end loop;

  -- targets (version 1; later changes are new versions made in admin)
  for item in select * from jsonb_array_elements(v_data -> 'targets') loop
    select id into v_tid from public.skill_test_types where program_id = p and code = item ->> 'test';
    if v_tid is not null and not exists (
      select 1 from public.skill_test_targets
      where test_type_id = v_tid and coalesce(level, 0) = (item ->> 'level')::int
    ) then
      insert into public.skill_test_targets (test_type_id, level, target_value, version)
      values (v_tid, (item ->> 'level')::smallint, (item ->> 'value')::numeric, 1);
    end if;
  end loop;

  -- rules
  for item in select * from jsonb_array_elements(v_data -> 'rules') loop
    v_gid := (v_groups ->> (item ->> 'skill'))::uuid;
    if not exists (
      select 1 from public.skill_rules
      where group_id = v_gid and coalesce(level, 0) = coalesce((item ->> 'level')::int, 0)
    ) then
      insert into public.skill_rules (group_id, level, mastery_min_score, min_evidence_sessions, requires_test)
      values (v_gid, nullif(item ->> 'level', '')::smallint, (item ->> 'mastery_min_score')::numeric,
              (item ->> 'min_evidence_sessions')::int, (item ->> 'requires_test')::boolean);
    end if;
  end loop;
end
$seed$;
